spring.application.name=booking-backend

spring.datasource.username=root
spring.datasource.password=Mysql@2005
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/BookMyAdda
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true